import { z } from 'zod';

export enum DeviceType {
  GROW_LIGHT = 1,
  HUMIDIFIER = 2,
  DEHUMIDIFIER = 3,
  HEATER = 4,
  AIR_CONDITION = 5,
  FAN = 6,
}

export enum DeviceMode {
  OFF = 1,
  ON = 2,
  AUTO = 3,
  TIMER_TO_ON = 4,
  TIMER_TO_OFF = 5,
  CYCLE = 6,
  SCHEDULE = 7,
  VPD = 8,
}

const DeviceBaseInputSchema = z.object({
  devId: z.string(),
  devMacAddr: z.string().nullable(),
  externalPort: z.number(),
  offSpead: z.number().min(0).max(10),
  onSpead: z.number().min(0).max(10),
  onSelfSpead: z.number(),
  ecUnit: z.number(),
  tdsUnit: z.number(),
  settingMode: z.number(),
  vpdSettingMode: z.number(),
  atType: z.enum(DeviceMode),
});

type DeviceBaseInput = z.input<typeof DeviceBaseInputSchema>;

const transformDeviceBase = ({ devId, externalPort, offSpead, onSpead, atType }: DeviceBaseInput) => ({
  id: devId,
  port: externalPort,
  levelWhileOff: offSpead,
  levelWhileOn: onSpead,
  mode: atType,
});

export const DeviceSettingsSchema = DeviceBaseInputSchema.extend({
  setId: z.string().nullable(),
  port: z.number(),
  devName: z.string().nullable(),
  devLight: z.number(),
  hasBacklightSwitch: z.number(),
  backlightSwitch: z.number(),
  hasKeytoneSwitch: z.number(),
  keytoneSwitch: z.number(),
  devCth: z.number(),
  devCt: z.number(),
  devCth2: z.number().nullable(),
  devCt2: z.number().nullable(),
  devCh: z.number(),
  devTt: z.number(),
  devTh: z.number(),
  devCompany: z.number(),
  devTth: z.number(),
  vpdCth: z.number(),
  vpdCt: z.number(),
  vpdTransition: z.number(),
  portResistance: z.number().nullable(),
  devBth: z.number(),
  devBt: z.number(),
  devBh: z.number(),
  devBvpd: z.number(),
  isFlag: z.number(),
  devTimeZone: z.string().nullable(),
  loadType: z.number(),
  tempCompare: z.number(),
  humiCompare: z.number(),
  onTimeSwitch: z.number(),
  onTime: z.number(),
  sensorSettingStr: z.string().nullable(),
  sensorSetting: z.unknown().nullable(),
  sensorTransBuffStr: z.string().nullable(),
  sensorTransBuff: z.unknown().nullable(),
  portParamData: z.string().nullable(),
  photocellSwitch: z.number(),
  isOpenDoseTime: z.number(),
  onDoseTime: z.number(),
  offDoseTime: z.number(),
  isOnMinMaxTime: z.number(),
  onMinTime: z.number(),
  onMaxTime: z.number(),
  ecOrTds: z.number(),
  interchangeSensor: z.number(),
  subDeviceId: z.string().nullable(),
  subDeviceVersion: z.string().nullable(),
  subDeviceType: z.number().nullable(),
  supportOta: z.unknown().nullable(),
  otaUpdating: z.unknown().nullable(),
  secFucStatus: z.number(),
  secFucDevtype: z.number(),
  secFucDevEffect: z.number(),
  secFucParamNums: z.number(),
  secFucParams: z.unknown().nullable(),
  secFucReportTime: z.number(),
  toward: z.unknown().nullable(),
  powerState: z.unknown().nullable(),
  updateAllPort: z.boolean(),
  timestamp: z.unknown().nullable(),
  calibrationTime: z.unknown().nullable(),
  fieldSet: z.array(z.unknown()),
  plantCode: z.number(),
  potSize: z.number(),
  plantingNum: z.number(),
  devCl: z.unknown().nullable(),
  devCsm1: z.unknown().nullable(),
  devCsm2: z.unknown().nullable(),
  devCsm3: z.unknown().nullable(),
  devCsm4: z.unknown().nullable(),
  uuidSta: z.number(),
  uuidType: z.unknown().nullable(),
  uuid: z.string().nullable(),
  matterCode: z.string().nullable(),
  matterSta: z.unknown().nullable(),
}).transform((v) => ({
  ...transformDeviceBase(v),
}));

export const DeviceModeSettingsSchema = DeviceBaseInputSchema.extend({
  acitveTimerOff: z.number(),
  acitveTimerOn: z.number(),
  activeCycleOff: z.number(),
  activeCycleOn: z.number(),
  activeHh: z.number(),
  activeHt: z.number(),
  activeHtVpd: z.number(),
  activeHtVpdNums: z.number(),
  activeLh: z.number(),
  activeLt: z.number(),
  activeLtVpd: z.number(),
  activeLtVpdNums: z.number(),
  co2FanHighSwitch: z.number(),
  co2FanHighValue: z.number(),
  co2LowSwitch: z.number(),
  co2LowValue: z.number(),
  devHh: z.number(),
  devHt: z.number(),
  devHtf: z.number(),
  devLh: z.number(),
  devLt: z.number(),
  devLtf: z.number(),
  ecTdsLowSwitchEc: z.number(),
  ecTdsLowSwitchTds: z.number(),
  ecTdsLowValueEcUs: z.number(),
  ecTdsLowValueTdsPpm: z.number(),
  isOpenAutomation: z.number(),
  modeType: z.number(),
  moistureLowSwitch: z.number(),
  moistureLowValue: z.number(),
  onlyUpdateSpeed: z.number(),
  phHighSwitch: z.number(),
  phHighValue: z.number(),
  phLowSwitch: z.number(),
  phLowValue: z.number(),
  schedEndtTime: z.number(),
  schedStartTime: z.number(),
  surplus: z.number().nullable(),
  targetHumi: z.number(),
  targetHumiSwitch: z.number(),
  targetTSwitch: z.number(),
  targetTemp: z.number(),
  targetTempF: z.number(),
  targetVpd: z.number(),
  targetVpdSwitch: z.number(),
  waterLevelLowSwitch: z.number(),
  waterTempHighSwitch: z.number(),
  waterTempHighValue: z.number(),
  waterTempHighValueF: z.number(),
  waterTempLowSwitch: z.number(),
  waterTempLowValue: z.number(),
  waterTempLowValueF: z.number(),
}).transform((v) => ({
  ...transformDeviceBase(v),
}));

export type DeviceSettings = z.infer<typeof DeviceSettingsSchema>;
export type DeviceModeSettings = z.infer<typeof DeviceModeSettingsSchema>;
export type DeviceModeSettingsInput = z.input<typeof DeviceModeSettingsSchema>;

export function encodeDeviceModeSettings(settings: Partial<DeviceModeSettings>): Partial<DeviceModeSettingsInput> {
  return {
    onSpead: settings.levelWhileOn,
  };
}
